services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Ubi2023!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
  mssqltools:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      - sqlserver
    volumes:
      - ./CreateTables.sql:/tmp/CreateTables.sql
      - ./Triggers.sql:/tmp/Triggers.sql
      - ./Procs.sql:/tmp/Procs.sql
      - ./init-mei_trab.sh:/tmp/init-mei_trab.sh
    command: /bin/bash ./tmp/init-mei_trab.sh